package fr.badblock.bungee.modules.ping;

import fr.badblock.bungee.link.bungee.BungeeManager;
import fr.badblock.bungee.modules.abstracts.BadListener;
import net.md_5.bungee.api.event.ProxyPingEvent;
import net.md_5.bungee.event.EventHandler;
import net.md_5.bungee.event.EventPriority;

/**
 * 
 * The purpose of this class is to manage the server motd
 * 
 * @author xMalware
 * 
 */
public class ProxyPingListener extends BadListener
{

	/**
	 * When someone ping the server
	 * @param event
	 */
	@EventHandler (priority = EventPriority.HIGHEST)
	public void onProxyPing(ProxyPingEvent event)
	{
		// We get the bungee manager
		BungeeManager bungeeManager = BungeeManager.getInstance();
		// We send him the response generated by our network synchronization system
		event.setResponse(bungeeManager.generatePing());
	}

}
