package fr.badblock.bungee.modules.friends;

public enum FriendListRequestStatus
{

	PLAYER_SCHIZOPHRENIA,
	PLAYERS_ALREADY_FRIENDS,
	PLAYERS_NOW_FRIENDS,
	PLAYER_ALREADY_REQUESTED,
	PLAYER_RECEIVE_REQUEST,
	PLAYER_DO_NOT_ACCEPT_REQUEST,
	UNKNOWN_ERROR

}